language: python

jobs:
  include:
    - name: "Python 3.6 on Linux"
      python: "3.6"

    - name: "Python 3.7 on Linux"
      python: "3.7"

    - name: "Python 3.8 on Linux"
      python: "3.8"
      dist: bionic

    - name: "Python 3.6 on Mac"
      os: osx
      osx_image: xcode9.4 # Python 3.6.5.
      language: shell
      #before_install:
      #  - brew install git-lfs.
      # this might be useful in the future - it's a large workspace
      install:
        - pip3 install --upgrade pip
        - pip3 install --user -r requirements.txt
      script: python3 -m pytest
      # we can add code coverage (codecov) here

    - name: "Python 3.6 on Windows"
      os: windows
      language: shell
      before_install:
        - choco install python --version 3.6.8
        - python -m pip install --upgrade pip
        env: PATH=/c/Python36:/c/Python36/Scripts:$PATH
install: pip3 install --upgrade pip
 
script:
  - pytest 